name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: uses: docker://tmknom/prh:latest
    - name: Check by prh
      run: prh --rules prh.yml --diff --verify **/*.re

